### PR TITLE
Add Github action for CI tests

### PR DESCRIPTION
**Pull request by rupurt**
First step in replacing Travis for CI

https://github.com/fremantle-capital/tai/actions
https://github.com/fremantle-capital/ex_bitmex/actions
https://github.com/features/actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions

### CODE REVIEW

**Comment by yurikoval** [comment]
Looks good. What do you think about having it run `bin/test` so you can trigger the same tests on local?

**Comment by rupurt** [comment]
Which steps are you thinking would go into the `bin/test` script? Something I like about the multiple steps is that there are UI controls to expand/collapse the section.

**Comment by yurikoval** [comment]
I'm fine with either way, I also like the UI separation as well.
Sometimes I forget to run everything, so I have a combined `bin/test`. `mix test` and `mix credo` can go together in one step and dialyzer can be separate.

**Comment by rupurt** [comment]
Ah, didn't realize there was an existing script for it. Just updated to use it.

**Pull request merged**
